/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as FloorPlanRouteImport } from './routes/floor-plan'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as PosRouteImport } from './routes/pos'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as StaffRouteImport } from './routes/staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlanRoute = FloorPlanRouteImport.update({
  id: '/floor-plan',
  path: '/floor-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/catalog': typeof CatalogRoute
  '/crew': typeof CrewRoute
  '/floor-plan': typeof FloorPlanRoute
  '/guests': typeof GuestsRoute
  '/inventory': typeof InventoryRoute
  '/jobs': typeof JobsRoute
  '/kitchen': typeof KitchenRoute
  '/packages': typeof PackagesRoute
  '/parts': typeof PartsRoute
  '/pos': typeof PosRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/scheduling': typeof SchedulingRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/catalog': typeof CatalogRoute
  '/crew': typeof CrewRoute
  '/floor-plan': typeof FloorPlanRoute
  '/guests': typeof GuestsRoute
  '/inventory': typeof InventoryRoute
  '/jobs': typeof JobsRoute
  '/kitchen': typeof KitchenRoute
  '/packages': typeof PackagesRoute
  '/parts': typeof PartsRoute
  '/pos': typeof PosRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/scheduling': typeof SchedulingRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/catalog': typeof CatalogRoute
  '/crew': typeof CrewRoute
  '/floor-plan': typeof FloorPlanRoute
  '/guests': typeof GuestsRoute
  '/inventory': typeof InventoryRoute
  '/jobs': typeof JobsRoute
  '/kitchen': typeof KitchenRoute
  '/packages': typeof PackagesRoute
  '/parts': typeof PartsRoute
  '/pos': typeof PosRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/scheduling': typeof SchedulingRoute
  '/staff': typeof StaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/billing'
    | '/bookings'
    | '/catalog'
    | '/crew'
    | '/floor-plan'
    | '/guests'
    | '/inventory'
    | '/jobs'
    | '/kitchen'
    | '/packages'
    | '/parts'
    | '/pos'
    | '/quotes'
    | '/reports'
    | '/rooms'
    | '/scheduling'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/billing'
    | '/bookings'
    | '/catalog'
    | '/crew'
    | '/floor-plan'
    | '/guests'
    | '/inventory'
    | '/jobs'
    | '/kitchen'
    | '/packages'
    | '/parts'
    | '/pos'
    | '/quotes'
    | '/reports'
    | '/rooms'
    | '/scheduling'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/billing'
    | '/bookings'
    | '/catalog'
    | '/crew'
    | '/floor-plan'
    | '/guests'
    | '/inventory'
    | '/jobs'
    | '/kitchen'
    | '/packages'
    | '/parts'
    | '/pos'
    | '/quotes'
    | '/reports'
    | '/rooms'
    | '/scheduling'
    | '/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BillingRoute: typeof BillingRoute
  BookingsRoute: typeof BookingsRoute
  CatalogRoute: typeof CatalogRoute
  CrewRoute: typeof CrewRoute
  FloorPlanRoute: typeof FloorPlanRoute
  GuestsRoute: typeof GuestsRoute
  InventoryRoute: typeof InventoryRoute
  JobsRoute: typeof JobsRoute
  KitchenRoute: typeof KitchenRoute
  PackagesRoute: typeof PackagesRoute
  PartsRoute: typeof PartsRoute
  PosRoute: typeof PosRoute
  QuotesRoute: typeof QuotesRoute
  ReportsRoute: typeof ReportsRoute
  RoomsRoute: typeof RoomsRoute
  SchedulingRoute: typeof SchedulingRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plan': {
      id: '/floor-plan'
      path: '/floor-plan'
      fullPath: '/floor-plan'
      preLoaderRoute: typeof FloorPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  BillingRoute: BillingRoute,
  BookingsRoute: BookingsRoute,
  CatalogRoute: CatalogRoute,
  CrewRoute: CrewRoute,
  FloorPlanRoute: FloorPlanRoute,
  GuestsRoute: GuestsRoute,
  InventoryRoute: InventoryRoute,
  JobsRoute: JobsRoute,
  KitchenRoute: KitchenRoute,
  PackagesRoute: PackagesRoute,
  PartsRoute: PartsRoute,
  PosRoute: PosRoute,
  QuotesRoute: QuotesRoute,
  ReportsRoute: ReportsRoute,
  RoomsRoute: RoomsRoute,
  SchedulingRoute: SchedulingRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
